// Recipes reducer constants
export const RECIPES_FETCH_DATA_REQUEST = "TESTS_FETCH_DATA_REQUEST";
export const RECIPES_FETCH_DATA_SUCCESS = "TESTS_FETCH_DATA_SUCCESS";
export const RECIPES_FETCH_DATA_FAILURE = "TESTS_FETCH_DATA_FAILURE";
