// Recipes reducer constants
export const RECIPES_FETCH_DATA_REQUEST = "RECIPES_FETCH_DATA_REQUEST";
export const RECIPES_FETCH_DATA_SUCCESS = "RECIPES_FETCH_DATA_SUCCESS";
export const RECIPES_FETCH_DATA_FAILURE = "RECIPES_FETCH_DATA_FAILURE";
export const RECIPES_ADD_NEW_RECIPE = "RECIPES_ADD_NEW_RECIPE";
export const RECIPES_SEND_RECIPE_CATEGORY = "RECIPES_SEND_RECIPE_CATEGORY";
export const RECIPES_SEND_RECIPE_COMMENT = "RECIPES_SEND_RECIPE_COMMENT";
export const RECIPES_DELETE_RECIPE_COMMENT = "RECIPES_DELETE_RECIPE_COMMENT";
